name: Approve pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request changes
        run: |
          # Check if the pull request contains changes to the README file
          if ! git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -q "README.md"; then
            echo "Pull request does not contain changes to README file"
            exit 1
          fi
          # Check if the pull request adds a new row to a table in the README file
          if ! git diff --unified=0 ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} README.md | grep -qE '^@@.*\+.*,0\s@@$'; then
            echo "Pull request does not add a new row to a table in README file"
            exit 1
          fi
          # Check if the table is working without errors
          if ! python3 validate_table.py README.md; then
            echo "Table contains errors"
            exit 1
          fi
          echo "Pull request is valid"
          exit 0
      - name: Approve pull request
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
          body: |
            {
              "event": "APPROVE"
            }
          headers: |
            {
              "Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}",
              "Accept": "application/vnd.github.v3+json"
            }
